require_relative 'binary_search_tree'

tree = BinarySearchTree.new
tree.insert(18, "matrix")
# tree.insert(13,"dumbness")
tree.insert(4,"Dark Knight")
tree.insert(1,"helloness")
tree.insert(3,"Dark Knight")
tree.insert(21,"helloness")
tree.insert(123,"helloness")
tree.insert(24,"helloness")
tree.insert(102,"matrix")
tree.insert(33,"helloness")
tree.insert(34,"Dark Knight")
tree.insert(222,"helloness")
tree.insert(143,"helloness")
tree.insert(154,"helloness")
tree.insert(223,"matrix")
tree.insert(12,"helloness")
tree.insert(14,"Dark Knight")
tree.insert(76,"helloness")
tree.insert(98,"helloness")
tree.insert(54,"helloness")
tree.insert(1234,"matrix")
tree.load('movies.txt')
